# Generated by Django 3.2.3 on 2021-05-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo del sensor')),
                ('lectura', models.FloatField(max_length=5, verbose_name='Lectura del medidor (Wh)')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de lectura')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_medidor', models.CharField(max_length=50, verbose_name='N° Medidor')),
                ('potencia', models.CharField(blank=True, max_length=50, verbose_name='Potencia (kWh)')),
                ('acometida', models.CharField(blank=True, max_length=50, verbose_name='Acometida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('sensor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.sensor', verbose_name='Sensor de medición')),
            ],
            options={
                'verbose_name': 'ElectricMeter',
                'verbose_name_plural': 'ElectricMeters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('codigo_cliente', models.CharField(max_length=50, verbose_name='Codigo del Cliente')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('medidor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.electricmeter', verbose_name='Medidor Electrico')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['id'],
            },
        ),
    ]
