# Generated by Django 3.2.3 on 2021-05-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeter',
            name='sensor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.sensor', verbose_name='Sensor de medición'),
        ),
    ]
