# Generated by Django 3.2.3 on 2021-05-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_electricmeter_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='codigo',
            field=models.CharField(max_length=50, null=True, verbose_name='Codigo del sensor'),
        ),
    ]
