# Generated by Django 3.2.3 on 2021-05-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210514_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='codigo_cliente',
        ),
        migrations.AddField(
            model_name='client',
            name='numero_suministro',
            field=models.CharField(max_length=50, null=True, verbose_name='N° Suministro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='medidor_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.electricmeter', verbose_name='Medidor Electrico'),
        ),
    ]
