# Generated by Django 3.2.3 on 2021-05-18 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210518_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='codigo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='lectura',
        ),
        migrations.AddField(
            model_name='sensor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectura_sensor', models.FloatField(blank=True, max_length=5, null=True, verbose_name='Lectura del sensor (Wh)')),
                ('fecha_sensado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de medicion')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.sensor')),
            ],
        ),
    ]
