# Generated by Django 3.2.3 on 2021-05-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210518_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='medidor_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='client_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
